#!/bin/sh
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
BIOS="$SCRIPTPATH"/u-boot-with-spl.bin
ln -sf "$SCRIPTPATH"/../tmp/qemu /tmp
truncate -s 16M $BIOS
QEMU="$SCRIPTPATH"/../tmp/qemu/bin/qemu-system-loongarch64
TFTP_DIR="$SCRIPTPATH"/../../../fs-img-dir
OS="$SCRIPTPATH"/nand.dat
[ -e "$OS" ] || dd if=/dev/zero bs=1M count=$(((256*(2048+64)/2048)))|tr '\000' '\377' > "$OS"
FS_IMG="$SCRIPTPATH"/rootfs-ubifs-ze.img

DEBUG_GMAC_PHYAD=0 "$QEMU"\
         -M ls2k -drive if=pflash,file=$BIOS,format=raw \
         -m 1024 \
         -D $SCRIPTPATH/qemu.log \
         -serial stdio \
         -drive if=mtd,file="$OS",format=raw \
         -net nic -net user,net=192.168.1.2/24,tftp=$TFTP_DIR \
         -net nic -net user,net=10.0.3.0/24\
         -vnc 0.0.0.0:0 \
         -smp threads=1 \
         -hda $FS_IMG \
         -s $@ 2>&1 \
