#!/bin/sh
# 获取当前脚本的绝对路径
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
# 创建符号链接，将脚本的上级目录下的tmp/qemu链接到/tmp
ln -sf "$SCRIPTPATH"/../tmp/qemu /tmp
# 配置BIOS文件路径
BIOS="$SCRIPTPATH"/u-boot-with-spl.bin
# 将BIOS文件大小截断为16M
# truncate -s 1M $BIOS
truncate -s 16M $BIOS
# 配置QEMU路径
QEMU="$SCRIPTPATH"/../tmp/qemu/bin/qemu-system-loongarch64
# 配置TFTP目录
TFTP_DIR="$SCRIPTPATH"/../../../fs-img-dir
# 配置OS文件路径
OS="$SCRIPTPATH"/nand.dat
# 检查OS文件是否存在，如果不存在则创建一个大小为256M的文件，
# 同时将文件中的所有字节设置为0xff，模拟 NAND 闪存的默认状态
# 64为oob的大小
# 该步会生成 nand.dat
[ -e "$OS" ] || dd if=/dev/zero bs=1M count=$(((256*(2048+64)/2048)))|tr '\000' '\377' > "$OS"

#-net nic -net user,net=10.0.2.1/24,tftp=$(pwd)
SERIAL=2 DEBUG_UNALIGN=1 DEBUG_GMAC_PHYAD=0 DEBUG_MYNAND=cs=0,id=0x2cda DEBUG_MYSPIFLASH=gd25q128 "$QEMU"\
         -M ls2k500 -drive if=pflash,file=$BIOS,format=raw \
         -m 2048M \
         -D $SCRIPTPATH/qemu.log \
         -serial stdio \
         -drive if=mtd,file="$OS",format=raw \
         -net nic -net user,net=192.168.1.2/24,tftp=$TFTP_DIR \
         -net nic -net user,net=10.0.3.0/24\
         -vnc 0.0.0.0:0 \
         -smp threads=1\
         -s $@
