[package]
name = "user_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
buddy_system_allocator = "0.8"
bitflags = "1.3.2"
[target.'cfg(target_arch = "loongarch64")'.dependencies]
rlibc = "1.0.0"

[profile.dev]
# debug = true
debug = 2